name: calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.1

flutter:
  uses-material-design: true